# Site settings
title: Collin's Place
description: > # this means to ignore newlines until "baseurl:"
  More coming soon!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://collinprice.com" # the base hostname & protocol for your site
twitter_username: collinprice
github_username:  collinprice

# Build settings
markdown: kramdown
